package edu.upenn.cis.utils;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.UUID;

@DynamoDBTable(tableName="url_to_docid")
public class UrlToDocId{

    private String url;
    private String docid;

    @DynamoDBHashKey(attributeName="url")
    public String getUrl() {
        return url;
    }
    public void setUrl(String url) {
        this.url = url;
    }

    @DynamoDBAttribute(attributeName="docid")
    public String getDocid() {
        return docid;
    }
    public void setDocid(String key) {
        this.docid = key;
    }

    public UrlToDocId() {
//        setDocid();
    }


}