package edu.upenn.cis.crawler.storage;

import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="url_to_docid")
public class UrlToDocIdItem {
	
	private String url;
	private String docid;
	
	 @DynamoDBHashKey(attributeName="url")
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	
	@DynamoDBAttribute(attributeName="docid")
	public String getDocid() {
		return docid;
	}
	public void setDocid() {
		this.docid = UUID.randomUUID().toString();
	}
	
	public UrlToDocIdItem() {
	}
	

}
